from webapi.db.Models.Questions import *
from webapi.db.Models.Answer import *
from webapi.db.Models.ChapterTheory import *
from webapi.db.Models.PointerToAnswer import *
from webapi.db.Models.ResultTest import *
from webapi.db.Models.Test import *
from webapi.db.Models.Theory import *
from webapi.db.Models.User import *
from webapi.db.Models.Base import *
