"""add field name in theory

Revision ID: 080f236d1315
Revises: 847f3492ae4d
Create Date: 2023-03-22 21:06:16.509605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080f236d1315'
down_revision = '847f3492ae4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'answers', ['id'])
    op.create_unique_constraint(None, 'answers_test', ['id'])
    op.create_unique_constraint(None, 'chapters_theory', ['id'])
    op.create_unique_constraint(None, 'pointers_to_answer', ['id'])
    op.create_unique_constraint(None, 'questions', ['id'])
    op.create_unique_constraint(None, 'questions_choice', ['id'])
    op.create_unique_constraint(None, 'questions_input_answer', ['id'])
    op.create_unique_constraint(None, 'questions_not_check', ['id'])
    op.create_unique_constraint(None, 'results_tests', ['id'])
    op.create_unique_constraint(None, 'tests', ['id'])
    op.add_column('theories', sa.Column('name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'theories', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'theories', type_='unique')
    op.drop_column('theories', 'name')
    op.drop_constraint(None, 'tests', type_='unique')
    op.drop_constraint(None, 'results_tests', type_='unique')
    op.drop_constraint(None, 'questions_not_check', type_='unique')
    op.drop_constraint(None, 'questions_input_answer', type_='unique')
    op.drop_constraint(None, 'questions_choice', type_='unique')
    op.drop_constraint(None, 'questions', type_='unique')
    op.drop_constraint(None, 'pointers_to_answer', type_='unique')
    op.drop_constraint(None, 'chapters_theory', type_='unique')
    op.drop_constraint(None, 'answers_test', type_='unique')
    op.drop_constraint(None, 'answers', type_='unique')
    # ### end Alembic commands ###
