"""add creator theory

Revision ID: 2d6fb5b80405
Revises: 96e7a96c946e
Create Date: 2023-11-25 09:04:50.192827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2d6fb5b80405'
down_revision = '96e7a96c946e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theories', sa.Column('creator_id', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'theories', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'theories', type_='foreignkey')
    op.drop_column('theories', 'creator_id')
    # ### end Alembic commands ###
