"""add as uuid

Revision ID: 2edb349145fd
Revises: 2d6fb5b80405
Create Date: 2023-11-25 10:46:38.966054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2edb349145fd'
down_revision = '2d6fb5b80405'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
