"""add_field_completed_date

Revision ID: 78cfd3d50681
Revises: fbf60ff24f18
Create Date: 2023-04-04 22:36:42.038387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78cfd3d50681'
down_revision = 'fbf60ff24f18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results_tests', sa.Column('completed_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results_tests', 'completed_date')
    # ### end Alembic commands ###
