"""add_nullable_note

Revision ID: 830384bce001
Revises: 78cfd3d50681
Create Date: 2023-04-04 22:56:31.813122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830384bce001'
down_revision = '78cfd3d50681'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('results_tests', 'note',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('results_tests', 'note',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
