"""remove_backref

Revision ID: 96e7a96c946e
Revises: 7621cb8159e2
Create Date: 2023-11-24 07:04:18.167354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e7a96c946e'
down_revision = '7621cb8159e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
