"""add_show_answer_and_note_for_test

Revision ID: fbf60ff24f18
Revises: 7a3837e36e67
Create Date: 2023-04-04 22:33:52.512464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbf60ff24f18'
down_revision = '7a3837e36e67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results_tests', sa.Column('note', sa.String(), nullable=False))
    op.add_column('tests', sa.Column('show_answer', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'show_answer')
    op.drop_column('results_tests', 'note')
    # ### end Alembic commands ###
